services:
  xybotv2:
    image: lhpmain/xybotv1:latest
    container_name: XYBotV21
    restart: on-failure:3
    ports:
      - "9999:9999"  # 映射gunicorn端口
    volumes:
      - xybotv2:/app
      - redis_data:/var/lib/redis

volumes:
  redis_data:
    name: redis_data
  xybotv2:
    name: xybotv21